export const SYSTEM = {
  SHOPIFY: "SHOPIFY",
  NETSUITE: "NETSUITE",
};

export const DIRECTION = {
  SHOPIFY_TO_NETSUITE: "SHOPIFY_TO_NETSUITE",
  NETSUITE_TO_SHOPIFY: "NETSUITE_TO_SHOPIFY",
};

export const EVENT_TYPE = {
  CREATE: "CREATE",
  UPDATE: "UPDATE",
  CANCEL: "CANCEL",
  FULFILL: "FULFILL",
};

export const STATUS = {
  RECEIVED: "RECEIVED",
  PENDING: "PENDING",
  SUCCESS: "SUCCESS",
  FAILED: "FAILED",
};
