export const DEFAULT_INVENTORY_MAPPINGS = [
  {
    netsuiteField: "itemId",
    shopifyField: "sku",
    transformType: "direct",
    isRequired: true,
    isActive: true,
    sortOrder: 1,
  },
  {
    netsuiteField: "displayName",
    shopifyField: "title",
    transformType: "direct",
    isRequired: false,
    isActive: true,
    sortOrder: 2,
  },
  {
    netsuiteField: "quantityAvailable",
    shopifyField: "inventoryQuantity",
    transformType: "direct",
    isRequired: true,
    isActive: true,
    sortOrder: 3,
  },
  {
    netsuiteField: "basePrice",
    shopifyField: "price",
    transformType: "direct",
    isRequired: false,
    isActive: true,
    sortOrder: 4,
  },
  {
    netsuiteField: "description",
    shopifyField: "descriptionHtml",
    transformType: "direct",
    isRequired: false,
    isActive: true,
    sortOrder: 5,
  },
];

export const DEFAULT_ORDER_MAPPINGS = [
  {
    netsuiteField: "entity",
    shopifyField: "customer.id",
    transformType: "lookup",
    transformConfig: { lookupTable: {} },
    isRequired: true,
    isActive: true,
    sortOrder: 1,
  },
  {
    netsuiteField: "tranDate",
    shopifyField: "createdAt",
    transformType: "direct",
    isRequired: true,
    isActive: true,
    sortOrder: 2,
  },
  {
    netsuiteField: "items",
    shopifyField: "lineItems",
    transformType: "custom",
    isRequired: true,
    isActive: true,
    sortOrder: 3,
  },
  {
    netsuiteField: "shippingCost",
    shopifyField: "totalShippingPriceSet.shopMoney.amount",
    transformType: "direct",
    isRequired: false,
    isActive: true,
    sortOrder: 4,
  },
  {
    netsuiteField: "memo",
    shopifyField: "note",
    transformType: "direct",
    isRequired: false,
    isActive: true,
    sortOrder: 5,
  },
];

export const DEFAULT_CUSTOMER_MAPPINGS = [
  {
    netsuiteField: "firstName",
    shopifyField: "firstName",
    transformType: "direct",
    isRequired: false,
    isActive: true,
    sortOrder: 1,
  },
  {
    netsuiteField: "lastName",
    shopifyField: "lastName",
    transformType: "direct",
    isRequired: false,
    isActive: true,
    sortOrder: 2,
  },
  {
    netsuiteField: "email",
    shopifyField: "email",
    transformType: "direct",
    isRequired: true,
    isActive: true,
    sortOrder: 3,
  },
  {
    netsuiteField: "phone",
    shopifyField: "phone",
    transformType: "direct",
    isRequired: false,
    isActive: true,
    sortOrder: 4,
  },
  {
    netsuiteField: "companyName",
    shopifyField: "company",
    transformType: "direct",
    isRequired: false,
    isActive: true,
    sortOrder: 5,
  },
  {
    netsuiteField: "defaultAddress",
    shopifyField: "defaultAddress",
    transformType: "custom",
    isRequired: false,
    isActive: true,
    sortOrder: 6,
  },
];
